/**
 * Default site content.
 *
 * This is the single source of truth used to seed MongoDB and as a fallback when
 * a content document is missing. Every string here is exactly what the original
 * hard-coded React components rendered, so a fresh database produces a
 * pixel-identical site.
 */

const GH = 'https://raw.githubusercontent.com/DrtSinX98/DrtSinX98.github.io/main/src/images';

export const IMAGE_BASE = GH;

export const defaultSite = {
  brand: 'Vortex',
  title: "Pritish's Vortex",
  description: 'Portfolio website of Pritish Joshi',
  nav: [
    { key: 'home', label: 'Home', href: '/', icon: 'house' },
    { key: 'about', label: 'About', href: '/about', icon: 'user' },
    { key: 'gallery', label: 'Gallery', href: '/gallery', icon: 'images' },
    { key: 'lectures', label: 'Lectures', href: '/lectures', icon: 'video' },
    { key: 'contact', label: 'Contact', href: '/contact', icon: 'message' },
  ],
  footer: {
    owner: 'Pritish Joshi',
    writtenIn: 'Written in',
  },
  theme: {
    primaryColor: '#301934',
    secondaryColor: '#c91574',
    tertiaryColor: '#eeeafc',
    primaryColorDark: '#130A15',
    dayStartHour: 6,
    nightStartHour: 18,
  },
  particles: {
    enabled: true,
    color: '#c91574',
    count: 150,
    speed: 2,
    linkDistance: 150,
    linkOpacity: 0.3,
    opacity: 0.4,
  },
  preloader: {
    enabled: true,
    images: [
      `${GH}/cyan.png`,
      `${GH}/twrp.png`,
      `${GH}/kern.png`,
      `${GH}/rui.png`,
      `${GH}/concetto.png`,
      `${GH}/stag.png`,
      `${GH}/kj.png`,
      `${GH}/mexb.png`,
      `${GH}/erec.png`,
      `${GH}/pfp_l.png`,
      `${GH}/pfp_d.png`,
      `${GH}/ab.svg`,
      `${GH}/pr.svg`,
      `${GH}/ct.svg`,
      `${GH}/lc.svg`,
      `${GH}/gl.svg`,
      `${GH}/grad.png`,
      `${GH}/work.png`,
      `${GH}/cert.png`,
      `${GH}/code.png`,
      `${GH}/hobby.png`,
      `${GH}/res.png`,
      `${GH}/pub.png`,
      `${GH}/teach.png`,
      `${GH}/social.png`,
      `${GH}/soft.png`,
      `${GH}/test.png`,
      `${GH}/thesis.png`,
      `${GH}/edu.png`,
      `${GH}/int.png`,
      `${GH}/wor.png`,
    ],
  },
};

export const defaultHome = {
  greetings: {
    morning: "G'morning",
    afternoon: "G'afternoon",
    evening: "G'evening",
    night: "G'night",
  },
  typewriter: ['Welcome!', "I'm Pritish Joshi"],
  tagline: 'A Tech enthusiast, Researcher, Educator and Coder',
  // `pink` marks the fragments rendered in the accent colour.
  intro: [
    { text: "I'm currently a " },
    { text: 'PhD Candidate', pink: true },
    { text: ' in Machine Learning at ' },
    { text: 'Uppsala University', pink: true },
    { text: ', Sweden. Previously, I worked on Computational Materials Discovery at ' },
    { text: 'TCG CREST', pink: true },
    { text: " and completed my Master's at " },
    { text: 'IIT Dhanbad', pink: true },
    { text: '.' },
  ],
  profileImageLight: `${GH}/pfp_l.png`,
  profileImageDark: `${GH}/pfp_d.png`,
  buttons: [
    { label: 'GitHub', icon: 'github', href: 'https://github.com/DrtSinX98' },
    { label: 'Scholar', icon: 'scholar', href: 'https://scholar.google.com/citations?user=jUdY7OcAAAAJ&hl=en' },
    { label: 'LinkedIn', icon: 'linkedin', href: 'https://linkedin.com/in/pritish-joshi-b870bb242' },
  ],
  terminal: {
    title: 'root@pritish:~',
    prompt: 'root@pritish:~#',
    command: 'cat whoami.json',
    name: 'Pritish Joshi',
    education: [
      'PhD Machine Learning - Uppsala University',
      'M.Sc Computational Chemistry - IIT Dhanbad',
      'B.Sc Chemistry Majors - IGNOU New Delhi',
    ],
    interests: [
      'Machine Learning',
      'Battery Modeling',
      'Coding',
      'Anime',
      'Photography',
      'Classical Music',
      'Philosophy',
    ],
    works: ['Research Project', 'Custom ROM Development', 'Web Development', 'Education'],
  },
};

export const defaultAbout = {
  image: `${GH}/ab.svg`,
  heading: [
    { text: 'Do you wanna know ' },
    { text: 'About me?', pink: true },
  ],
  lead: [
    { text: "I'm a guy who likes to learn new things and explore different fields." },
    { br: true },
    { text: "I'm " },
    { text: 'currently', pink: true },
    { text: ' a researcher in the field of Machine Learning.' },
    { br: true },
    { br: true },
    { text: 'If interested, you can look into my ' },
    { cv: true, text: 'Curriculum vitae' },
    { br: true },
    { br: true },
    { text: 'You can also find more details ' },
    { text: 'about me', pink: true },
    { text: ' down below.' },
  ],
  journeyTitle: 'Journey',
  journey: [
    {
      title: 'Uppsala University',
      subtitle: 'PhD Candidate | Machine Learning-Information Technology',
      tags: ['Machine Learning', 'Battery Modeling', 'Deep Learning'],
    },
    {
      title: 'RISE, TCG CREST',
      subtitle: 'Project Associate | Computational Materials Discovery',
      tags: ['Metal-ion Batteries', 'Density Functional Theory', 'Neural Networks'],
    },
    {
      title: 'IIT Dhanbad',
      subtitle: 'Master of Science | Computational Chemistry-Chemical Biology',
      tags: ['Computational Chemistry', 'Machine Learning', 'Molecular Dynamics'],
    },
  ],
  skillsTitle: 'Tech Stack & Tools',
  skillGroups: [
    {
      title: 'Programming Languages',
      icon: 'desktop',
      variant: 'solid',
      items: ['Python', 'C++', 'JavaScript', 'React.js', 'HTML5', 'CSS3'],
    },
    {
      title: 'Machine Learning & Scientific Software',
      icon: 'microscope',
      variant: 'outline',
      items: [
        'PyTorch',
        'Tensorflow',
        'Transformers',
        'PINNs',
        'AMBER',
        'GROMACS',
        'NAMD',
        'Quantum Espresso',
        'VASP',
        'Gaussian',
      ],
    },
    {
      title: 'Utilities & Design',
      icon: 'book',
      variant: 'soft',
      items: ['Figma', 'Origin', 'LaTEX', 'Jupyter Notebook'],
    },
  ],
  projectsTitle: 'Projects & Portfolios',
  projectTabs: [
    {
      key: 'android',
      title: 'Android / Kernel',
      projects: [
        {
          title: 'Cyanide Project',
          desc: 'Lead Developer of Cyanide custom ROM project that is built on top of Lineage OS with various features and Redesigned User Interface',
          icon: 'mobileScreen',
          link: 'https://github.com/Los-FE',
        },
        {
          title: 'TWRP Spaced',
          desc: 'Official maintainer of TeamWin Recovery Project for Realme 8i (spaced). TWRP is a Custom Recovery used to flash custom partitions in device',
          icon: 'wrench',
          link: 'https://twrp.me/realme/realme8i.html',
        },
        {
          title: 'Cyanide Kernel',
          desc: 'Developer of Cyanide Kernel for Realme 8i and 8s 5G. Cyanide kernel is a Custom Kernel with various device specific tweaks and optimizations',
          icon: 'microchip',
          link: 'https://xdaforums.com/t/kernel-4-14-cyanide-kernel-1-0-for-realme-8i-spaced.4447145/',
        },
        {
          title: 'Realme Debloater',
          desc: 'Scripts for removing unwanted apps from realme UI 2.0 and higher. Realme UI comes with lots of bloatwares, this script helps removing those.',
          icon: 'broom',
          link: 'https://github.com/DrtSinX98/Debloat',
        },
      ],
    },
    {
      key: 'design',
      title: 'Design / UI',
      projects: [
        {
          title: 'Concetto 2023',
          desc: 'Co-head of Design & Content Team in Concetto 2023. Concetto is the annual Techno-management fest of IIT Dhanbad',
          icon: 'palette',
          link: 'http://www.concetto.in/',
        },
        {
          title: 'Stag OS',
          desc: 'Designer and Device Maintainer at Stag OS. Stag OS is a custom ROM project based on Android Open Source Project with various features',
          icon: 'mobileScreen',
          link: 'https://stag-os.org',
        },
        {
          title: 'Karmajyoti',
          desc: 'Head of Media & Branding and Web Developer at KarmaJyoti. KarmaJyoti is a Philanthropic organisation under CSM, IIT (ISM) Dhanbad',
          icon: 'handHoldingHeart',
          link: 'https://karmajyoti.org',
        },
      ],
    },
    {
      key: 'comp',
      title: 'Computational',
      projects: [
        {
          title: 'MexB Inhibitors',
          desc: 'DST (SERB) Funded Project: Prediction of MexB Efflux Pump Inhibitors: A complete Machine Learning and Molecular Dynamics approach',
          icon: 'dna',
          link: 'https://doi.org/10.1021/acs.jpcb.3c05845',
        },
        {
          title: 'EreC Dynamics',
          desc: 'MSc Thesis Project: Molecular Dynamics of Erethromycin Esterase (EreC): Binding Mechanism with Erythromycin and Azithromycin',
          icon: 'atom',
          link: 'https://drive.google.com/file/d/1C5NlFdb0n3bDihn7Gv2fDqKNTCHAO9Iv/view?usp=share_link',
        },
      ],
    },
  ],
  achievementsTitle: 'Achievements & Certifications',
  publicationsTitle: 'Publications & Thesis',
  publications: [
    {
      title: '"Inverse Design of Next-generation Battery Materials via Diffusion-Seeded Evolutionary Optimization"',
      subtitle: 'Submitted',
      link: '#',
    },
    {
      title: '"Reactive dynamics study of solid electrolytes Li6PS5Cl|Li3InCl6 interface: an ab initio molecular dynamics simulation"',
      subtitle: 'Submitted',
      link: '#',
    },
    {
      title: '"Delving into Macrolide Binding Affinities and Associated Structural Modulations in Erythromycin Esterase C: Insights into the Venus Flytrap Mechanism"',
      subtitle: 'Journal of Chemical Information and Modeling | Nov 20, 2024',
      link: 'https://doi.org/10.1021/acs.jcim.4c01523',
    },
    {
      title: '"Machine Learning-Guided Discovery of AcrB and MexB Efflux Pump Inhibitors"',
      subtitle: 'Journal of Physical Chemistry B | ACS | Jan 10, 2024',
      link: 'https://doi.org/10.1021/acs.jpcb.3c05845',
    },
    {
      title: "Master's Thesis: Revolutionising Antibacterial Warfare",
      subtitle: 'Machine Learning and Molecular Dynamics Unveiling Potential Gram-Negative Bacteria Inhibitors | May 2024',
      link: 'https://drive.google.com/file/d/1C5NlFdb0n3bDihn7Gv2fDqKNTCHAO9Iv/view?usp=share_link',
    },
  ],
  examsTitle: 'National Level Exams',
  exams: [
    { title: 'GATE (CY) 2025', subtitle: 'All India Rank 951', link: '#' },
    {
      title: 'GATE (CY) 2024',
      subtitle: 'All India Rank 569',
      link: 'https://drive.google.com/file/d/1-9eYgxvBIuBHXsMnHDHcUEjxhlNe0YXe/view?usp=sharing',
    },
    { title: 'CSIR NET 2024', subtitle: 'Qualified', link: '#' },
    {
      title: 'IIT JAM (CY) 2022',
      subtitle: 'All India Rank 443',
      link: 'https://drive.google.com/file/d/11UGuILn-M0cD1Z3E6P09FomcU2I_5nPV/view?usp=sharing',
    },
  ],
  certificatesTitle: 'Online Certifications',
  certificates: [
    { title: 'Getting Started with Python (University of Michigan)', link: 'https://www.coursera.org/account/accomplishments/verify/MZK5JE7VPKW7' },
    { title: 'Python Data Structure (University of Michigan)', link: 'https://www.coursera.org/account/accomplishments/verify/AJSMZSQEQ9BD' },
    { title: 'Python Accessing Web Data (University of Michigan)', link: 'https://www.coursera.org/account/accomplishments/certificate/WVVBUSHR5LQN' },
    { title: 'Crash Course on Python (Google)', link: 'https://www.coursera.org/account/accomplishments/verify/8KUEY6QESMCC' },
    { title: 'Python Libraries (UpGrad)', link: 'https://upgrad.verification.givemycertificate.com/v/0ab0419e-8abc-48ef-be63-a53457c5bae6' },
    { title: 'Supervised Machine Learning (Stanford Online)', link: 'https://www.coursera.org/account/accomplishments/certificate/JZYVMBGZJMH8' },
    { title: 'Machine Learning Basic to Advanced (Udemy)', link: 'https://www.udemy.com/certificate/UC-9ae61440-df14-4edc-ba0b-0bdb1dd08791/' },
    { title: 'Data Science and ML Workshop (Coding Ninjas)', link: 'https://drive.google.com/file/d/1PYbt1QVUkwaaW_Laa0trcnD8eCLoYmNg/view?usp=sharing' },
    { title: 'Data Science Foundations (Great Learning)', link: 'https://olympus.mygreatlearning.com/courses/13680/certificate' },
    { title: 'Introduction to Cryptography (Wolfram U)', link: 'https://www.wolframcloud.com/obj/online-courses/introduction-to-cryptography/api/userData/certificates/ace2f595-f53b-4aed-bfe8-f3b25a58a426_CC.pdf' },
    { title: 'HTML, CSS & JavaScript (Johns Hopkins University)', link: 'https://www.coursera.org/account/accomplishments/verify/F2HFNKMRSU8C' },
    { title: 'JavaScript & React.Js (Microsoft)', link: 'https://www.cert.devtown.in/verify/2etySg' },
    { title: 'JavaScript & React.Js (Google)', link: 'https://www.cert.devtown.in/verify/ZDgt6s' },
    { title: 'JavaScript & React.Js (DevTown)', link: 'https://www.cert.devtown.in/verify/ZUK79h' },
    { title: 'HTML (Sololearn)', link: 'https://www.sololearn.com/Certificate/CT-ZBLJ6PY7/pdf' },
    { title: 'Getting Started with Figma (Coursera)', link: 'https://www.coursera.org/account/accomplishments/verify/MAR5Z2LL9PFD' },
  ],
  highlights: [
    {
      icon: 'chalkboardTeacher',
      title: 'Teaching',
      desc: '5 years experience in science for boards and competitive exams.',
      badges: ['IIT JEE (Chem)', 'NEET (Chem)', 'XI & XII (PCM)'],
    },
    {
      icon: 'gamepad',
      title: 'Hobbies',
      desc: 'Leisure activities and pastimes.',
      badges: ['Anime', 'Frontend Dev', 'Android Dev', 'Graphic Design', 'Gaming'],
    },
    {
      icon: 'users',
      title: 'Socials',
      desc: 'Connect with me across the web.',
      links: [
        { label: 'LinkedIn', href: 'https://www.linkedin.com/in/pritish-joshi-b870bb242' },
        { label: 'Instagram', href: 'https://www.instagram.com/the_istreet' },
      ],
    },
  ],
};

export const defaultCv = {
  fileName: 'Pritish_Joshi_CV.pdf',
  name: 'Pritish Ranjan Joshi',
  subtitle: 'PhD Candidate in Machine Learning',
  email: 'pritish.ranjan.joshi@it.uu.se',
  location: 'Uppsala, Sweden',
  website: { label: 'www.pritish.eu', href: 'https://www.pritish.eu' },
  socials: [
    { label: 'LinkedIn', icon: 'linkedin', href: 'https://www.linkedin.com/in/pritish-joshi-b870bb242/' },
    { label: 'GitHub', icon: 'github', href: 'https://github.com/DrtSinX98' },
    { label: 'Scholar', icon: 'google', href: 'https://scholar.google.com/citations?hl=en&user=jUdY7OcAAAAJ' },
  ],
  summaryTitle: 'Summary',
  summaryIntro:
    'An adaptable and motivated researcher with a deep interest and curiosity in interdisciplinary science and technology:',
  summaryPoints: [
    'Currently working on simulation-guided inference for modeling of metal plating dynamics in batteries.',
    'Previously worked on variational autoencoders, predictive modeling, quantum and classical mechanical simulation for battery materials.',
    'Have also worked with classical MD simulations and ML based predictions of drugs and bio-molecules.',
  ],
  skillsTitle: 'Technical Skills',
  skillGroups: [
    { title: 'Programming', items: ['Python', 'C++', 'JavaScript', 'HTML', 'CSS', 'ReactJS', 'Shell Scripting'] },
    { title: 'Machine Learning', items: ['Bayesian models', 'PINNs', 'Transformers', 'Variational Auto-Encoders'] },
    { title: 'Data Analysis', items: ['Pandas', 'NumPy', 'MatPlotLib', 'Seaborn', 'Yellowbrick', 'Origin'] },
    { title: 'Software & Tools', items: ['PyTorch', 'Tensorflow', 'Quantum Espresso', 'VASP'] },
    { title: 'Computational Modelling', items: ['Classical MD', 'ab initio MD', 'Docking', 'DFT'] },
  ],
  testScoresTitle: 'Test Scores',
  testScores: [
    { label: 'IIT GATE 2025:', value: 'AIR 951' },
    { label: 'IIT GATE 2024:', value: 'AIR 569' },
    { label: 'CSIR NET 2024:', value: 'Qualified' },
    { label: 'IIT JAM 2022:', value: 'AIR 443' },
  ],
  experienceTitle: 'Research Experience',
  experience: [
    {
      org: 'Uppsala University',
      place: '| Uppsala, SE',
      date: '2025 - Present',
      role: 'PhD Student',
      points: [
        'Simulation-guided inference for modeling of metal plating dynamics in batteries.',
        'Phase-Field modeling of electroplating dynamics.',
        'PINN based FEM solvers.',
      ],
      noteLabel: 'Supervisors:',
      note: 'Jens Sjölund, Peter Broqvist, Erik Berg',
    },
    {
      org: 'RISE, TCG CREST',
      place: '| Kolkata, IN',
      date: '2024 - 2025',
      role: 'Project Associate',
      points: [
        'Computational Materials Discovery using Conditional Variational Autoencoders.',
        'Reactive Dynamics study of Batteries using DFT and ML-FF.',
        'Interfacial reaction dynamics of electrolytes using Classical and ab initio MD.',
      ],
      noteLabel: 'Supervisors:',
      note: 'Tanmoy Paul, Gour P. Das',
    },
    {
      org: 'IIT (ISM) Dhanbad',
      place: '| Dhanbad, IN',
      date: '2023 - 2024',
      role: "Master's Thesis Project",
      points: [
        'Machine Learning guided drug discovery.',
        'Classical and semi-classical molecular dynamics simulation and analysis.',
      ],
      noteLabel: 'Supervisor:',
      note: 'Niladri Patra',
    },
  ],
  educationTitle: 'Education',
  education: [
    {
      org: 'Uppsala University',
      place: '| Uppsala, SE',
      date: '2025 - Present',
      role: 'Doctor of Philosophy, Machine Learning-Information Technology',
      noteLabel: 'Key courses:',
      note: 'Statistical Machine Learning, Deep Learning, Convex Optimization, Advanced Python',
    },
    {
      org: 'Indian Institute of Technology (ISM)',
      place: '| Dhanbad, IN',
      date: '2022 - 2024',
      role: 'Master of Science, Computational Chemistry-Chemical Biology',
      noteLabel: 'Key courses:',
      note: 'Machine Learning, Quantum Chemistry, Statistical Thermodynamics, Mathematics for Chemists...',
    },
    {
      org: 'IGNO University',
      place: '| New Delhi, IN',
      date: '2019 - 2021',
      role: 'Bachelor of Science, Chemistry-Mathematics',
    },
  ],
  publicationsTitle: 'Publications',
  publications: [
    {
      title: 'Inverse Design of Next-generation Battery Materials via Diffusion-Seeded Evolutionary Optimization',
      date: 'Submitted',
      authors: 'Pritish Joshi, Arnob Das, Rajdeep Boral, Tanmoy Paul',
    },
    {
      title: 'Reactive dynamics study of solid electrolytes Li6PS5Cl|Li3InCl6 interface: an ab initio molecular dynamics simulation',
      date: 'Submitted',
      authors: 'Pritish Joshi, Tanmoy Paul',
    },
    {
      title: 'Delving into Macrolide Binding Affinities and Associated Structural Modulations in Erythromycin Esterase C: Insights into the Venus Flytrap Mechanism',
      link: 'https://doi.org/10.1021/acs.jcim.4c01523',
      journal: 'Journal of Chemical Information and Modeling (20-11-2024)',
      authors: 'Abhishek Bera, Pritish Joshi, Niladri Patra',
    },
    {
      title: 'Machine Learning-Guided Discovery of AcrB and MexB Efflux Pump Inhibitors',
      link: 'https://doi.org/10.1021/acs.jpcb.3c05845',
      journal: 'Journal of Physical Chemistry B (10-01-2024)',
      authors: 'Abhishek Bera, Rakesh Kumar Roy, Pritish Joshi, Niladri Patra',
    },
  ],
};

export const defaultGallery = {
  image: `${GH}/gl.svg`,
  heading: [{ text: 'Welcome to my ' }, { text: 'Gallery!', pink: true }],
  lead: [
    { text: 'I love to travel a lot and have travelled to many places in ' },
    { text: 'India', pink: true },
    { text: ' and ' },
    { text: 'abroad', pink: true },
    { text: '. ' },
    { br: true },
    { text: 'As I have some interest in ' },
    { text: 'photography', pink: true },
    { text: ', I try to click pictures of monuments, architecture, and nature. ' },
    { br: true },
    { text: 'Below you can find a beautifully curated gallery of the pictures taken from my ' },
    { text: 'phone', pink: true },
    { text: '.' },
  ],
  totalCountries: 195,
  mapHeadline: 'Explore the world through my lens.',
  mapSubline: 'Click on my highlighted visited countries to see some wonderful pictures!',
  visitedListTitle: 'Visited Countries',
  backLabel: '← Back to Map',
  emptyLabel: 'No photos available for {country} yet.',
  weatherLoadingLabel: 'Fetching atmosphere...',
};

export const defaultLectures = {
  image: `${GH}/lc.svg`,
  heading: [{ text: 'Enjoy the ' }, { text: 'Lectures!', pink: true }],
  lead: [
    { text: 'I am planning to prepare a ' },
    { text: 'lecture ', pink: true },
    { text: 'series on' },
    { br: true },
    { text: 'Computational ', pink: true },
    { text: 'Physics, Chemistry, and Biology.' },
    { br: true },
    { text: 'Below you can look into the ' },
    { text: 'topics ', pink: true },
    { text: 'that will be covered in this series.' },
    { br: true },
    { text: 'Links will be updated as soon as the videos are ready ' },
    { text: '(weekly)', pink: true },
    { text: '.' },
  ],
  modules: [
    {
      header: 'Module 1',
      title: 'The Fundamentals',
      split: true,
      topics: [
        {
          title: 'Mathematics: Fundamentals - I',
          subtopics: ['Functions', 'Calculus', 'Vectors', 'Linear algebra', 'Matrices'],
        },
        {
          title: 'Mathematics: Fundamentals - II',
          subtopics: ['Commplex numbers', 'Vector calculus', 'Series expansion', 'Operator algebra', 'Bra-Ket notations'],
        },
        {
          title: 'Statistics: Fundamentals - I',
          subtopics: [
            'Types of statistics',
            'Understanding data',
            'Population vs. samples',
            'Data distributions',
            'Central tendencies',
            'The Gaussian distribution',
            'Measure of dispersion',
            'Measure of shape',
          ],
        },
        {
          title: 'Statistics: Fundamentals - II',
          subtopics: [
            'Statistical distances',
            'Outliers',
            'Principal Component Analysis',
            'Probability theory',
            'Hypothesis testing',
            'ANOVA',
            'Chi-square test',
            'Bayesian statistics',
          ],
        },
        {
          title: 'Proteins & Membrane structure',
          subtopics: [
            'Amino acids',
            'peptide linkages',
            'primary, secondary and tertiary structures',
            'Interaction of proteins and ligands',
            'lipids and membranes',
          ],
        },
        {
          title: 'Solid state physics',
          subtopics: [
            'Crystal systems and Lattices',
            'Point groups and space groups',
            'Unit cell',
            'Super cell',
            'wigner - Seitz cell',
            'Reciprocal space',
            'k-points and Brillouin zone',
            "X-Ray diffraction: Bragg's law and Laue's law",
            'Defects in crystals',
          ],
        },
      ],
    },
    {
      header: 'Module 2',
      title: 'Classical Molecular Dynamics',
      split: true,
      topics: [
        {
          title: 'Introduction to Classical Mechanics',
          subtopics: [
            'The classical regime',
            'Mass and velocity',
            'Formalisms of classical mechanics',
            'Applicability',
            'Limitations',
          ],
        },
        {
          title: 'Newtonian Mechanics',
          subtopics: [
            'Degrees of freedom',
            '1D motion of a single particle',
            'Phase space and phase portrait',
            'Dynamics in phase space',
            'Linear dynamical systems',
            'Autonomous dynamical systems',
            'Conservative vs. dissipated systems',
            'Limitations of Newtonian formalism',
          ],
        },
        {
          title: 'Lagrangian Mechanics',
          subtopics: ['Action principles', 'The Lagrangian', 'Newtonian to Lagrangian', 'Advantages and Limitations'],
        },
        {
          title: 'Hamiltonian Mechanics',
          subtopics: [
            'Legendre transformations',
            'Lagrangian to Hamiltonian',
            "Hamilton's equation",
            'Constants of motion',
            "Poisson's brackets",
            'Hamiltonian for a general dynamical system',
            'Free mmotion of a particle on a line',
            'Solving a Hamiltonian',
            'Canonical transformations',
            'Origin of dynamical chaos',
            'Ergodicity',
            "Noether's Theorem",
            'Dynamical symmetry groups',
          ],
        },
        {
          title: 'Equilibrium Statistical Mechanics',
          subtopics: [
            'Introduction',
            'Probability Distributions',
            'Ensembles',
            'Thermodynamics & Statistical Mechanics Relation',
            'Phase Transitions',
          ],
        },
        {
          title: 'Non-Equilibrium Statistical Mechanics',
          subtopics: ['The Langevin Model', 'Linear Response Theory'],
        },
        {
          title: 'Classical Molecular Dynamics',
          subtopics: [
            'Applicability',
            'Short & Long range interactions',
            'Integrators',
            'Thermodynamic Ensembles',
            'Thermostats and Barostats',
            'Boundary Conditions',
            'Parallel MD',
          ],
        },
        {
          title: 'Classical Force Fields',
          subtopics: [
            'Structure of a Force Field',
            'Intramolecular Terms',
            'Intermolecular Terms',
            'Special Terms',
            'Popular Force Fields',
            'Parametrizing a Force Field',
            'Beyond empirical Force Field',
          ],
        },
        {
          title: 'Free Energy Calculations & sampling Methods',
          subtopics: [
            'Solvation/Transfer Free Energy',
            'Binding Free Energy',
            'Conformational Free Energy',
            'Calculation of Free Energy',
            'Brute Force Method',
            'Thermodynamical Integration',
            'Free Energy Perturbation',
            'Umbrella Sampling',
            'Potential of Mean Force',
            'Steered Molecular Dynamics',
            'Adaptive Biased Force',
            'Replica Exchange/Parallel Tempering',
          ],
        },
        {
          title: 'Entropy corrections',
          subtopics: [
            'Harmonic and Quasi-harmonic techniques',
            'Step-by-step reconstruction',
            'Normal Mode Analysis',
            'Interaction Entropy',
          ],
        },
        {
          title: 'Minimum Energy Paths of Transition',
          subtopics: ['Chain-of-states/Plain Elastic Bands', 'Nudge Elastic Bands', 'Implementation of NEB'],
        },
        {
          title: 'QM/MM methods',
          subtopics: [
            'Hybrid QM/MM Methods',
            'Subtractive QM/MM Methods',
            'Additive QM/MM Methods',
            'Capping bonds at QM/MM boundary',
          ],
        },
        { title: 'Hands on CMD soft matter', subtopics: [] },
        { title: 'Hands on CMD hard matter', subtopics: [] },
      ],
    },
    {
      header: 'Module 3',
      title: 'ab initio Molecular Dynamics',
      split: false,
      topics: [
        { title: 'Introduction to Quantum Mechanics', subtopics: [] },
        { title: 'Copenhagen vs. Bohemian interpretations', subtopics: [] },
        { title: 'Schrödinger, Heisenberg, and Dirac formalisms', subtopics: [] },
        { title: 'Approximation Methods', subtopics: [] },
        { title: 'Wave function based methods (Hartree-Fock method and beyond)', subtopics: [] },
        { title: 'Density based methods (Density Functional Theory and beyond)', subtopics: [] },
        { title: 'ab initio Molecular Dynamics', subtopics: [] },
        { title: 'Hand on AIMD: Structural relaxation', subtopics: [] },
        { title: 'Hands on AIMD: Simulations of liquids and solids', subtopics: [] },
        { title: 'Hand on AIMD: Slab models and Interfaces', subtopics: [] },
        { title: 'Introduction to Electronic Structure Theory', subtopics: [] },
        { title: 'Hands on Electronic Structure Calculations', subtopics: [] },
      ],
    },
    {
      header: 'Module 4',
      title: 'Python Programming',
      split: false,
      topics: [
        { title: 'Introduction to Python programming language', subtopics: [] },
        { title: 'Data types and variables', subtopics: [] },
        { title: 'Conditionals', subtopics: [] },
        { title: 'Loops', subtopics: [] },
        { title: 'Hands on basic python programming', subtopics: [] },
        { title: 'Python Libraries', subtopics: [] },
        { title: 'Numpy, Pandas and Matplotlib', subtopics: [] },
        { title: 'Hands on python programming with libraries', subtopics: [] },
      ],
    },
    {
      header: 'Module 5',
      title: 'Machine Learning',
      split: false,
      topics: [
        { title: 'Introduction to Machine Learning', subtopics: [] },
        { title: 'Regression problems', subtopics: [] },
        { title: 'Classification Problems', subtopics: [] },
        { title: 'Tree based models', subtopics: [] },
        { title: 'Support Vector Machines', subtopics: [] },
        { title: 'Bagging and Boosting techniques', subtopics: [] },
        { title: 'Bayesian Statistics and Bayes’ Theorem: The Naïve Bayes Algorithm', subtopics: [] },
        { title: 'Hands on ML: Regression', subtopics: [] },
        { title: 'Hands on ML: Classification', subtopics: [] },
        { title: 'Machine Learning in Physics, Chemistry and Biology', subtopics: [] },
        { title: 'Machine Learning Force Fields', subtopics: [] },
      ],
    },
    {
      header: 'Module 6',
      title: 'Deep Learning',
      split: false,
      topics: [
        { title: 'Introduction to Deep Learning', subtopics: [] },
        { title: 'Artificial neurons', subtopics: [] },
        { title: 'Activation function', subtopics: [] },
        { title: 'Neural Networks', subtopics: [] },
        { title: 'ANN, RNN, CNN and GNN', subtopics: [] },
        { title: 'Image processing', subtopics: [] },
        { title: 'Generative Adversarial Networks (GANs)', subtopics: [] },
        { title: 'Variational Auto-Encoders (VAEs)', subtopics: [] },
        { title: 'Neural Networks in Physics, Chemistry and Biology', subtopics: [] },
      ],
    },
  ],
};

export const defaultContact = {
  image: `${GH}/ct.svg`,
  heading: [{ text: 'Reach out ' }, { text: 'to me!', pink: true }],
  leadPrefix: [
    { text: "I'm available on " },
    { text: 'Linkedin', pink: true },
    { text: ', Twitter, Telegram, Whatsapp, Discord, and Instagram. ' },
    { br: true },
    { text: 'You can ' },
  ],
  emailButtonLabel: 'E-Mail',
  email: 'rjpritish@gmail.com',
  leadSuffix: ' me directly or find my contact details below, feel free to reach out.',
  cards: [
    { title: 'LinkedIn', icon: 'linkedin', text: 'Connect with me on LinkedIn', href: 'https://www.linkedin.com/in/pritish-joshi-b870bb242' },
    { title: 'Twitter', icon: 'xTwitter', text: 'Follow me on Twitter (X)', highlight: 'X', href: 'https://x.com/rjpritish' },
    { title: 'Telegram', icon: 'telegram', text: 'Chat with me on Telegram', href: 'https://t.me/rj_pritish' },
    { title: 'Whatsapp', icon: 'whatsapp', text: 'Join me on Whatsapp', href: 'https://wa.me/pritishranjanjoshi' },
    { title: 'Instagram', icon: 'instagram', text: 'Join my channel on Instagram', href: 'https://www.instagram.com/the_istreet' },
    { title: 'Discord', icon: 'discord', text: 'Message me on Discord', href: 'https://discordapp.com/users/rjpritish_08301' },
  ],
  form: {
    enabled: true,
    title: 'Send me a message',
    nameLabel: 'Name',
    namePlaceholder: 'Enter full name',
    emailLabel: 'Email address',
    emailPlaceholder: 'name@example.com',
    messageLabel: 'Message',
    messagePlaceholder: 'Enter your message',
    submitLabel: 'Submit',
    submittingLabel: 'Sending...',
    successMessage: 'Message sent successfully!',
    errorMessage: 'Something went wrong. Please try again.',
  },
};

/** Country metadata, previously `src/data/countryData.json` + the flag/city maps in Gallery.jsx. */
export const defaultCountries = [
  { name: 'India', flag: '🇮🇳', displayName: 'Republic of India', continent: 'Asia', capital: 'New Delhi', area: '3,287,263 km²', population: '1.4 Billion', greeting: 'Namaste', mapCenter: [78.9629, 20.5937], mapZoom: 4, lat: 28.6139, lng: 77.209, visited: true, order: 0 },
  { name: 'Sweden', flag: '🇸🇪', displayName: 'Kingdom of Sweden', continent: 'Europe', capital: 'Stockholm', area: '450,295 km²', population: '10.4 Million', greeting: 'Hej', mapCenter: [18.6435, 60.1282], mapZoom: 3, lat: 59.3293, lng: 18.0686, visited: true, order: 1 },
  { name: 'Thailand', flag: '🇹🇭', displayName: 'Kingdom of Thailand', continent: 'Asia', capital: 'Bangkok', area: '513,120 km²', population: '69.8 Million', greeting: 'Sawasdee', mapCenter: [100.9925, 15.87], mapZoom: 4, lat: 13.7563, lng: 100.5018, visited: true, order: 2 },
  { name: 'Turkey', flag: '🇹🇷', displayName: 'Republic of Türkiye', continent: 'Europe/Asia', capital: 'Ankara', area: '783,562 km²', population: '84.3 Million', greeting: 'Merhaba', mapCenter: [35.2433, 38.9637], mapZoom: 5, lat: 39.9334, lng: 32.8597, visited: true, order: 3 },
  { name: 'Qatar', flag: '🇶🇦', displayName: 'State of Qatar', continent: 'Asia', capital: 'Doha', area: '11,586 km²', population: '2.8 Million', greeting: 'Marhaba', mapCenter: [51.1839, 25.3548], mapZoom: 20, lat: 25.2854, lng: 51.531, visited: true, order: 4 },
  { name: 'Finland', flag: '🇫🇮', displayName: 'Republic of Finland', continent: 'Europe', capital: 'Helsinki', area: '338,424 km²', population: '5.5 Million', greeting: 'Hei', mapCenter: [25.7482, 61.9241], mapZoom: 3, lat: 60.1695, lng: 24.9354, visited: true, order: 5 },
  { name: 'Norway', flag: '🇳🇴', displayName: 'Kingdom of Norway', continent: 'Europe', capital: 'Oslo', area: '323,802 km²', population: '5.4 Million', greeting: 'Hallo', mapCenter: [8.4689, 60.472], mapZoom: 3, lat: 59.9139, lng: 10.7522, visited: true, order: 6 },
  { name: 'Estonia', flag: '🇪🇪', displayName: 'Republic of Estonia', continent: 'Europe', capital: 'Tallinn', area: '45,227 km²', population: '1.3 Million', greeting: 'Tere', mapCenter: [25.0136, 58.5953], mapZoom: 9, lat: 59.437, lng: 24.7536, visited: true, order: 7 },
  { name: 'Latvia', flag: '🇱🇻', displayName: 'Republic of Latvia', continent: 'Europe', capital: 'Riga', area: '64,589 km²', population: '1.9 Million', greeting: 'Sveiki', mapCenter: [24.6032, 56.8796], mapZoom: 8, lat: 56.9496, lng: 24.1052, visited: true, order: 8 },
  { name: 'Lithuania', flag: '🇱🇹', displayName: 'Republic of Lithuania', continent: 'Europe', capital: 'Vilnius', area: '65,300 km²', population: '2.8 Million', greeting: 'Labas', mapCenter: [23.8813, 55.1694], mapZoom: 8, lat: 54.6872, lng: 25.2797, visited: true, order: 9 },
  { name: 'Poland', flag: '🇵🇱', displayName: 'Republic of Poland', continent: 'Europe', capital: 'Warsaw', area: '312,696 km²', population: '37.9 Million', greeting: 'Cześć', mapCenter: [19.1451, 51.9194], mapZoom: 5, lat: 52.2297, lng: 21.0122, visited: true, order: 10 },
  { name: 'Denmark', flag: '🇩🇰', displayName: 'Kingdom of Denmark', continent: 'Europe', capital: 'Copenhagen', area: '43,094 km²', population: '5.8 Million', greeting: 'Hej', mapCenter: [9.5018, 56.2639], mapZoom: 8, lat: 55.6761, lng: 12.5683, visited: true, order: 11 },
  { name: 'Germany', flag: '🇩🇪', displayName: 'Federal Republic of Germany', continent: 'Europe', capital: 'Berlin', area: '357,022 km²', population: '83.2 Million', greeting: 'Hallo', mapCenter: [10.4515, 51.1657], mapZoom: 5, lat: 52.52, lng: 13.405, visited: true, order: 12 },
  { name: 'Hungary', flag: '🇭🇺', displayName: 'Hungary', continent: 'Europe', capital: 'Budapest', area: '93,028 km²', population: '9.7 Million', greeting: 'Szia', mapCenter: [19.5033, 47.1625], mapZoom: 7, lat: 47.4979, lng: 19.0402, visited: true, order: 13 },
  { name: 'Italy', flag: '🇮🇹', displayName: 'Italian Republic', continent: 'Europe', capital: 'Rome', area: '301,340 km²', population: '60.4 Million', greeting: 'Ciao', mapCenter: [12.5674, 41.8719], mapZoom: 5, lat: 41.9028, lng: 12.4964, visited: true, order: 14 },
];

/** Folder name -> label shown in the gallery (was `cityDisplayNames` in Gallery.jsx). */
export const cityDisplayNames = {
  Poznan: 'Poznań',
  Vasteras: 'Västerås',
};

export const CONTENT_DEFAULTS = {
  site: defaultSite,
  home: defaultHome,
  about: defaultAbout,
  cv: defaultCv,
  gallery: defaultGallery,
  lectures: defaultLectures,
  contact: defaultContact,
};
