/**
 * Named icons available to editable content.
 *
 * Content documents store an icon *name* (e.g. "mobileScreen") rather than an
 * imported object, so the admin panel can offer a picker and the database stays
 * JSON-serialisable.
 */
import {
  faHouse,
  faUser,
  faVideo,
  faImages,
  faMessage,
  faFilePdf,
  faGraduationCap,
  faBriefcase,
  faMicroscope,
  faCode,
  faDesktop,
  faTrophy,
  faBook,
  faChalkboardTeacher,
  faGamepad,
  faUsers,
  faProjectDiagram,
  faMobileScreen,
  faWrench,
  faMicrochip,
  faBroom,
  faPalette,
  faHandHoldingHeart,
  faDna,
  faAtom,
  faTemperatureHalf,
  faDroplet,
  faCloudRain,
  faClock,
  faEnvelope,
  faPhone,
  faMapMarkerAlt,
  faGlobe,
  faFileAlt,
  faAward,
  faStar,
  faSave,
  faSun,
  faMoon,
  faFlask,
  faLightbulb,
  faRocket,
  faServer,
  faDatabase,
  faChartLine,
  faCamera,
  faMusic,
  faHeart,
  faLink,
} from '@fortawesome/free-solid-svg-icons';
import {
  faGithub,
  faLinkedin,
  faGoogleScholar,
  faGoogle,
  faXTwitter,
  faTelegram,
  faWhatsapp,
  faInstagram,
  faDiscord,
  faReact,
  faBootstrap,
  faYoutube,
  faFacebook,
  faMastodon,
  faReddit,
  faStackOverflow,
  faOrcid,
} from '@fortawesome/free-brands-svg-icons';

export const ICONS = {
  // navigation
  house: faHouse,
  user: faUser,
  video: faVideo,
  images: faImages,
  message: faMessage,
  // sections
  filePdf: faFilePdf,
  graduationCap: faGraduationCap,
  briefcase: faBriefcase,
  microscope: faMicroscope,
  code: faCode,
  desktop: faDesktop,
  trophy: faTrophy,
  book: faBook,
  chalkboardTeacher: faChalkboardTeacher,
  gamepad: faGamepad,
  users: faUsers,
  projectDiagram: faProjectDiagram,
  // projects
  mobileScreen: faMobileScreen,
  wrench: faWrench,
  microchip: faMicrochip,
  broom: faBroom,
  palette: faPalette,
  handHoldingHeart: faHandHoldingHeart,
  dna: faDna,
  atom: faAtom,
  flask: faFlask,
  lightbulb: faLightbulb,
  rocket: faRocket,
  server: faServer,
  database: faDatabase,
  chartLine: faChartLine,
  camera: faCamera,
  music: faMusic,
  heart: faHeart,
  link: faLink,
  // weather / misc
  temperature: faTemperatureHalf,
  droplet: faDroplet,
  cloudRain: faCloudRain,
  clock: faClock,
  envelope: faEnvelope,
  phone: faPhone,
  mapMarker: faMapMarkerAlt,
  globe: faGlobe,
  fileAlt: faFileAlt,
  award: faAward,
  star: faStar,
  save: faSave,
  sun: faSun,
  moon: faMoon,
  // brands
  github: faGithub,
  linkedin: faLinkedin,
  scholar: faGoogleScholar,
  google: faGoogle,
  xTwitter: faXTwitter,
  telegram: faTelegram,
  whatsapp: faWhatsapp,
  instagram: faInstagram,
  discord: faDiscord,
  react: faReact,
  bootstrap: faBootstrap,
  youtube: faYoutube,
  facebook: faFacebook,
  mastodon: faMastodon,
  reddit: faReddit,
  stackOverflow: faStackOverflow,
  orcid: faOrcid,
};

/** Falls back to a neutral link glyph so a bad name never crashes a page. */
export function getIcon(name) {
  return ICONS[name] || faLink;
}

export const ICON_NAMES = Object.keys(ICONS);
